export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';

export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL';

export const QUESTION_DETAILS_REQUEST = 'QUESTION_DETAILS_REQUEST';
export const QUESTION_DETAILS_SUCCESS = 'QUESTION_DETAILS_SUCCESS';
export const QUESTION_DETAILS_FAIL = 'QUESTION_DETAILS_FAIL';

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST';
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS';
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL';

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST';
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS';
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL';

export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST';
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS';
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'

export const TOP_UP_PACKAGE_LIST_REQUEST = 'TOP_UP_PACKAGE_LIST_REQUEST';
export const TOP_UP_PACKAGE_LIST_SUCCESS = 'TOP_UP_PACKAGE_LIST_SUCCESS';
export const TOP_UP_PACKAGE_LIST_FAIL = 'TOP_UP_PACKAGE_LIST_FAIL';

export const TOP_UP_PACKAGE_DETAILS_REQUEST = 'TOP_UP_PACKAGE_DETAILS_REQUEST';
export const TOP_UP_PACKAGE_DETAILS_SUCCESS = 'TOP_UP_PACKAGE_DETAILS_SUCCESS';
export const TOP_UP_PACKAGE_DETAILS_FAIL = 'TOP_UP_PACKAGE_DETAILS_FAIL';

export const TOP_UP_PACKAGE_UPDATE_REQUEST = 'TOP_UP_PACKAGE_UPDATE_REQUEST';
export const TOP_UP_PACKAGE_UPDATE_SUCCESS = 'TOP_UP_PACKAGE_UPDATE_SUCCESS';
export const TOP_UP_PACKAGE_UPDATE_FAIL = 'TOP_UP_PACKAGE_UPDATE_FAIL';

export const TOP_UP_PACKAGE_DELETE_REQUEST = 'TOP_UP_PACKAGE_DELETE_REQUEST';
export const TOP_UP_PACKAGE_DELETE_SUCCESS = 'TOP_UP_PACKAGE_DELETE_SUCCESS';
export const TOP_UP_PACKAGE_DELETE_FAIL = 'TOP_UP_PACKAGE_DELETE_FAIL';

export const TOP_UP_PACKAGE_CREATE_REQUEST = 'TOP_UP_PACKAGE_CREATE_REQUEST';
export const TOP_UP_PACKAGE_CREATE_SUCCESS = 'TOP_UP_PACKAGE_CREATE_SUCCESS';
export const TOP_UP_PACKAGE_CREATE_FAIL = 'TOP_UP_PACKAGE_CREATE_FAIL';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';

export const COMMENT_DETAILS_REQUEST = 'COMMENT_DETAILS_REQUEST';
export const COMMENT_DETAILS_SUCCESS = 'COMMENT_DETAILS_SUCCESS';
export const COMMENT_DETAILS_FAIL = 'COMMENT_DETAILS_FAIL';

export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';