export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const CREATE_COMMENT_VOTE_REQUEST = 'CREATE_COMMENT_VOTE_REQUEST';
export const CREATE_COMMENT_VOTE_SUCCESS = 'CREATE_COMMENT_VOTE_SUCCESS';
export const CREATE_COMMENT_VOTE_FAIL = 'CREATE_COMMENT_VOTE_FAIL';

export const UPDATE_POINTS_REQUEST = 'UPDATE_POINTS_REQUEST';
export const UPDATE_POINTS_SUCCESS = 'UPDATE_POINTS_SUCCESS';
export const UPDATE_POINTS_FAILURE = 'UPDATE_POINTS_FAILURE';