export const GET_USER_POINTS_REQUEST = 'GET_USER_POINTS_REQUEST';
export const GET_USER_POINTS_SUCCESS = 'GET_USER_POINTS_SUCCESS';
export const GET_USER_POINTS_FAIL = 'GET_USER_POINTS_FAIL';

export const TOP_UP_PACKAGES_REQUEST = 'TOP_UP_PACKAGES_REQUEST';
export const TOP_UP_PACKAGES_SUCCESS = 'TOP_UP_PACKAGES_SUCCESS';
export const TOP_UP_PACKAGES_FAIL = 'TOP_UP_PACKAGES_FAIL';

export const PURCHASE_POINTS_REQUEST = 'PURCHASE_POINTS_REQUEST';
export const PURCHASE_POINTS_SUCCESS = 'PURCHASE_POINTS_SUCCESS';
export const PURCHASE_POINTS_FAIL = 'PURCHASE_POINTS_FAIL';

export const GET_PACKAGE_DETAILS_REQUEST = 'GET_PACKAGE_DETAILS_REQUEST';
export const GET_PACKAGE_DETAILS_SUCCESS = 'GET_PACKAGE_DETAILS_SUCCESS';
export const GET_PACKAGE_DETAILS_FAIL = 'GET_PACKAGE_DETAILS_FAIL';