export const ACTIVATE_PREMIUM_REQUEST = 'ACTIVATE_PREMIUM_REQUEST';
export const ACTIVATE_PREMIUM_SUCCESS = 'ACTIVATE_PREMIUM_SUCCESS';
export const ACTIVATE_PREMIUM_FAILURE = 'ACTIVATE_PREMIUM_FAILURE';

export const GET_PREMIUM_DETAILS_REQUEST = 'GET_PREMIUM_DETAILS_REQUEST';
export const GET_PREMIUM_DETAILS_SUCCESS = 'GET_PREMIUM_DETAILS_SUCCESS';
export const GET_PREMIUM_DETAILS_FAILURE = 'GET_PREMIUM_DETAILS_FAILURE';
