    export const ASK_QUESTION_REQUEST = 'ASK_QUESTION_REQUEST';
    export const ASK_QUESTION_SUCCESS = 'ASK_QUESTION_SUCCESS';
    export const ASK_QUESTION_FAIL = 'ASK_QUESTION_FAIL';

    export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
    export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
    export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL';

    export const QUESTION_DETAIL_REQUEST = 'QUESTION_DETAIL_REQUEST';
    export const QUESTION_DETAIL_SUCCESS = 'QUESTION_DETAIL_SUCCESS';
    export const QUESTION_DETAIL_FAIL = 'QUESTION_DETAIL_FAIL';