    export const ASK_QUESTION_REQUEST = 'ASK_QUESTION_REQUEST';
    export const ASK_QUESTION_SUCCESS = 'ASK_QUESTION_SUCCESS';
    export const ASK_QUESTION_FAIL = 'ASK_QUESTION_FAIL';

    export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
    export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS';
    export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL';

    export const QUESTION_DETAIL_REQUEST = 'QUESTION_DETAIL_REQUEST';
    export const QUESTION_DETAIL_SUCCESS = 'QUESTION_DETAIL_SUCCESS';
    export const QUESTION_DETAIL_FAIL = 'QUESTION_DETAIL_FAIL';

    export const FETCH_SEARCH_RESULTS_REQUEST = 'FETCH_SEARCH_RESULTS_REQUEST';
    export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
    export const FETCH_SEARCH_RESULTS_FAIL = 'FETCH_SEARCH_RESULTS_FAIL';

    export const USER_QUESTIONS_REQUEST = 'USER_QUESTIONS_REQUEST';
    export const USER_QUESTIONS_SUCCESS = 'USER_QUESTIONS_SUCCESS';
    export const USER_QUESTIONS_FAIL = 'USER_QUESTIONS_FAIL';
