export const UPLOAD_IMAGE_ENGLISH_REQUEST = 'UPLOAD_IMAGE_ENGLISH_REQUEST';
export const UPLOAD_IMAGE_ENGLISH_SUCCESS = 'UPLOAD_IMAGE_ENGLISH_SUCCESS';
export const UPLOAD_IMAGE_ENGLISH_FAIL = 'UPLOAD_IMAGE_ENGLISH_FAIL';

export const GET_UPLOADED_IMAGES_ENGLISH_REQUEST = 'GET_UPLOADED_IMAGES_ENGLISH_REQUEST';
export const GET_UPLOADED_IMAGES_ENGLISH_SUCCESS = 'GET_UPLOADED_IMAGES_ENGLISH_SUCCESS';
export const GET_UPLOADED_IMAGES_ENGLISH_FAIL = 'GET_UPLOADED_IMAGES_ENGLISH_FAIL';

export const UPLOAD_IMAGE_HISTORY_REQUEST = 'UPLOAD_IMAGE_HISTORY_REQUEST';
export const UPLOAD_IMAGE_HISTORY_SUCCESS = 'UPLOAD_IMAGE_HISTORY_SUCCESS';
export const UPLOAD_IMAGE_HISTORY_FAIL = 'UPLOAD_IMAGE_HISTORY_FAIL';

export const GET_UPLOADED_IMAGES_HISTORY_REQUEST = 'GET_UPLOADED_IMAGES_HISTORY_REQUEST';
export const GET_UPLOADED_IMAGES_HISTORY_SUCCESS = 'GET_UPLOADED_IMAGES_HISTORY_SUCCESS';
export const GET_UPLOADED_IMAGES_HISTORY_FAIL = 'GET_UPLOADED_IMAGES_HISTORY_FAIL';

export const UPLOAD_IMAGE_MATH_REQUEST = 'UPLOAD_IMAGE_MATH_REQUEST';
export const UPLOAD_IMAGE_MATH_SUCCESS = 'UPLOAD_IMAGE_MATH_SUCCESS';
export const UPLOAD_IMAGE_MATH_FAIL = 'UPLOAD_IMAGE_MATH_FAIL';

export const GET_UPLOADED_IMAGES_MATH_REQUEST = 'GET_UPLOADED_IMAGES_MATH_REQUEST';
export const GET_UPLOADED_IMAGES_MATH_SUCCESS = 'GET_UPLOADED_IMAGES_MATH_SUCCESS';
export const GET_UPLOADED_IMAGES_MATH_FAIL = 'GET_UPLOADED_IMAGES_MATH_FAIL';

export const UPLOAD_IMAGE_SCIENCE_REQUEST = 'UPLOAD_IMAGE_SCIENCE_REQUEST';
export const UPLOAD_IMAGE_SCIENCE_SUCCESS = 'UPLOAD_IMAGE_SCIENCE_SUCCESS';
export const UPLOAD_IMAGE_SCIENCE_FAIL = 'UPLOAD_IMAGE_SCIENCE_FAIL';

export const GET_UPLOADED_IMAGES_SCIENCE_REQUEST = 'GET_UPLOADED_IMAGES_SCIENCE_REQUEST';
export const GET_UPLOADED_IMAGES_SCIENCE_SUCCESS = 'GET_UPLOADED_IMAGES_SCIENCE_SUCCESS';
export const GET_UPLOADED_IMAGES_SCIENCE_FAIL = 'GET_UPLOADED_IMAGES_SCIENCE_FAIL';

export const UPLOAD_IMAGE_PHYSICS_REQUEST = 'UPLOAD_IMAGE_PHYSICS_REQUEST';
export const UPLOAD_IMAGE_PHYSICS_SUCCESS = 'UPLOAD_IMAGE_PHYSICS_SUCCESS';
export const UPLOAD_IMAGE_PHYSICS_FAIL = 'UPLOAD_IMAGE_PHYSICS_FAIL';

export const GET_UPLOADED_IMAGES_PHYSICS_REQUEST = 'GET_UPLOADED_IMAGES_PHYSICS_REQUEST';
export const GET_UPLOADED_IMAGES_PHYSICS_SUCCESS = 'GET_UPLOADED_IMAGES_PHYSICS_SUCCESS';
export const GET_UPLOADED_IMAGES_PHYSICS_FAIL = 'GET_UPLOADED_IMAGES_PHYSICS_FAIL';

export const UPLOAD_IMAGE_CALCULUS_REQUEST = 'UPLOAD_IMAGE_CALCULUS_REQUEST';
export const UPLOAD_IMAGE_CALCULUS_SUCCESS = 'UPLOAD_IMAGE_CALCULUS_SUCCESS';
export const UPLOAD_IMAGE_CALCULUS_FAIL = 'UPLOAD_IMAGE_CALCULUS_FAIL';

export const GET_UPLOADED_IMAGES_CALCULUS_REQUEST = 'GET_UPLOADED_IMAGES_CALCULUS_REQUEST';
export const GET_UPLOADED_IMAGES_CALCULUS_SUCCESS = 'GET_UPLOADED_IMAGES_CALCULUS_SUCCESS';
export const GET_UPLOADED_IMAGES_CALCULUS_FAIL = 'GET_UPLOADED_IMAGES_CALCULUS_FAIL';