export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';

export const GET_UPLOADED_IMAGES_REQUEST = 'GET_UPLOADED_IMAGES_REQUEST';
export const GET_UPLOADED_IMAGES_SUCCESS = 'GET_UPLOADED_IMAGES_SUCCESS';
export const GET_UPLOADED_IMAGES_FAIL = 'GET_UPLOADED_IMAGES_FAIL';

export const UPDATE_USER_DESCRIPTION_REQUEST = 'UPDATE_USER_DESCRIPTION_REQUEST';
export const UPDATE_USER_DESCRIPTION_SUCCESS = 'UPDATE_USER_DESCRIPTION_SUCCESS';
export const UPDATE_USER_DESCRIPTION_FAIL = 'UPDATE_USER_DESCRIPTION_FAIL';

export const FETCH_USER_DESCRIPTION_REQUEST = 'FETCH_USER_DESCRIPTION_REQUEST';
export const FETCH_USER_DESCRIPTION_SUCCESS = 'FETCH_USER_DESCRIPTION_SUCCESS';
export const FETCH_USER_DESCRIPTION_FAIL = 'FETCH_USER_DESCRIPTION_FAIL';

export const UPLOAD_PROFILE_IMAGE_REQUEST = 'UPLOAD_PROFILE_IMAGE_REQUEST';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAIL = 'UPLOAD_PROFILE_IMAGE_FAIL';

export const GET_PROFILE_IMAGE_REQUEST = 'GET_PROFILE_IMAGE_REQUEST';
export const GET_PROFILE_IMAGE_SUCCESS = 'GET_PROFILE_IMAGE_SUCCESS';
export const GET_PROFILE_IMAGE_FAIL = 'GET_PROFILE_IMAGE_FAIL';