# Generated by Django 5.0.2 on 2024-04-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='totalDownvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='totalUpvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
